/*
Global Flood Mapper (GFM) Version 2

This script precomputes dictionary containing country names
and their constituting sub-regions. We use FAO GAUL 2015
admin level 1 polygons for this.

Find information about the GFM project on the GitHub repository:
https://github.com/PratyushTripathy/global_flood_mapper
*/

function getAdminBoundaryNames(){
  
  var aoi = ee.FeatureCollection("FAO/GAUL/2015/level1");
  
  //Extract the list of countries from the global boundary layer
  var country = ee.List(aoi.reduceColumns(ee.Reducer.toList(), ['ADM0_NAME']).get('list')).distinct()
  
  // Create a function to map on the country names
  // list and get the names of all the states
  function get_level1_list(level_0_name){
    var level_0_filtered = aoi.filter(ee.Filter.equals('ADM0_NAME', level_0_name));
    var level_1_list = ee.List(level_0_filtered.reduceColumns(ee.Reducer.toList(), ['ADM1_NAME']).get('list')).distinct().sort();
    
    return level_1_list;
  }
  
  return ee.Dictionary.fromLists(country, country.map(get_level1_list));
}

/*
Run the below part to print the dictionary in the console. 
Once printed, paste it below to re-use it.
*/
//var country_states = getAdminBoundaryNames();
//print(country_states);

var country_names = {
  "Abyei": [
    "Administrative unit not available"
  ],
  "Afghanistan": [
    "Badakhshan",
    "Badghis",
    "Baghlan",
    "Balkh",
    "Bamyan",
    "Daykundi",
    "Farah",
    "Faryab",
    "Ghazni",
    "Ghor",
    "Hilmand",
    "Hirat",
    "Jawzjan",
    "Kabul",
    "Kandahar",
    "Kapisa",
    "Khost",
    "Kunar",
    "Kunduz",
    "Laghman",
    "Logar",
    "Nangarhar",
    "Nimroz",
    "Nuristan",
    "Paktika",
    "Paktya",
    "Panjsher",
    "Parwan",
    "Samangan",
    "Sar-e-Pul",
    "Takhar",
    "Uruzgan",
    "Wardak",
    "Zabul"
  ],
  "Aksai Chin": [
    "Administrative unit not available"
  ],
  "Albania": [
    "Berat",
    "Bulqize",
    "Delvine",
    "Devoll",
    "Diber",
    "Durres",
    "Elbasan",
    "Fier",
    "Gjirokaster",
    "Gramsh",
    "Has",
    "Kavaje",
    "Kolonje",
    "Korce",
    "Kruje",
    "Kucove",
    "Kukes",
    "Kurbin",
    "Lezhe",
    "Librazhd",
    "Lushnje",
    "Malesi E Madhe",
    "Mallakaster",
    "Mat",
    "Mirdite",
    "Peqin",
    "Permet",
    "Pogradec",
    "Puke",
    "Sarande",
    "Shkoder",
    "Skrapar",
    "Tepelene",
    "Tirane",
    "Tropoje",
    "Vlore"
  ],
  "Algeria": [
    "Adrar",
    "Ain-Defla",
    "Ain-Temouchent",
    "Alger",
    "Annaba",
    "Batna",
    "Bechar",
    "Bejaia",
    "Biskra",
    "Blida",
    "Bordj Bou Arrer",
    "Bouira",
    "Boumerdes",
    "Chlef",
    "Constantine",
    "Djelfa",
    "El Bayadh",
    "El Oued",
    "El-Tarf",
    "Ghardaia",
    "Guelma",
    "Illizi",
    "Jijel",
    "Khenchela",
    "Laghouat",
    "M'Sila",
    "Mascara",
    "Medea",
    "Mila",
    "Mostaganem",
    "Naama",
    "Oran",
    "Ouargla",
    "Oum El Bouaghi",
    "Relizane",
    "Saida",
    "Setif",
    "Sidi Bel Abbes",
    "Skikda",
    "Souk-Ahras",
    "Tamanrasset",
    "Tebessa",
    "Tiaret",
    "Tindouf",
    "Tipaza",
    "Tissemsilt",
    "Tizi Ouzou",
    "Tlemcen"
  ],
  "American Samoa": [
    "Administrative unit not available"
  ],
  "Andorra": [
    "Andorra La Vella",
    "Canillo",
    "Encamp",
    "Escaldes-engordany",
    "La Massana",
    "Ordino",
    "Sant Julia De Loria"
  ],
  "Angola": [
    "Bengo",
    "Benguela",
    "Bie",
    "Cabinda",
    "Cuando Cubango",
    "Cuanza Sul",
    "Cunene",
    "Huambo",
    "Huila",
    "Kuanza Norte",
    "Luanda",
    "Lunda Norte",
    "Lunda Sul",
    "Malanje",
    "Moxico",
    "Namibe",
    "Uige",
    "Zaire"
  ],
  "Anguilla": [
    "Name Unknown"
  ],
  "Antarctica": [
    "Administrative unit not available"
  ],
  "Antigua and Barbuda": [
    "Barbuda",
    "Name Unknown",
    "St. George",
    "St. John",
    "St. Mary",
    "St. Paul",
    "St. Peter",
    "St. Philip"
  ],
  "Argentina": [
    "Buenos Aires",
    "Buenos Aires D.f.",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Cordoba",
    "Corrientes",
    "Entre Rios",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquen",
    "Rio Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago Del Estero",
    "Tierra Del Fuego",
    "Tucuman"
  ],
  "Armenia": [
    "Aragatsotn",
    "Ararat",
    "Armavir",
    "Gergharkunik",
    "Kotayk",
    "Lori",
    "Shirak",
    "Syunik",
    "Tavush",
    "Vayots Dzor",
    "Yerevan"
  ],
  "Aruba": [
    "Administrative unit not available"
  ],
  "Arunachal Pradesh": [
    "Administrative unit not available"
  ],
  "Ashmore and Cartier Islands": [
    "Administrative unit not available"
  ],
  "Australia": [
    "Australian Capital Territory",
    "Coral Sea Islands Territory",
    "New South Wales",
    "Northern Territory",
    "Other Territories",
    "Queensland",
    "South Australia",
    "Tasmania",
    "Victoria",
    "Western Australia"
  ],
  "Austria": [
    "Burgenland",
    "Karnten",
    "Niederosterreich",
    "Oberosterreich",
    "Salzburg",
    "Steiermark",
    "Tirol",
    "Vorarlberg",
    "Wien"
  ],
  "Azerbaijan": [
    "Absheron",
    "Administrative unit not available",
    "Aran",
    "Daghlig Shirvan",
    "Ganja-Gazakh",
    "Guba-Khachmaz",
    "Kalbajar-Lachin",
    "Lankaran",
    "Nakhchivan",
    "Shaki-Zaqatala",
    "Yukhari Garabakh"
  ],
  "Azores Islands": [
    "Ilha Da Graciosa (acores)",
    "Ilha Das Flores (acores)",
    "Ilha De Santa Maria (acores)",
    "Ilha De Sao Jorge (acores)",
    "Ilha De Sao Miguel (acores)",
    "Ilha Do Corvo (acores)",
    "Ilha Do Faial (acores)",
    "Ilha Do Pico (acores)",
    "Ilha Terceira (acores)"
  ],
  "Bahamas": [
    "Administrative unit not available"
  ],
  "Bahrain": [
    "Central Region",
    "Hamad Town",
    "Hawar Island",
    "Hidd",
    "Isa Town",
    "Jidhafs",
    "Manama",
    "Muharraq",
    "Northern Region",
    "Riffa",
    "Sitra",
    "Western Region"
  ],
  "Baker Island": [
    "Administrative unit not available"
  ],
  "Bangladesh": [
    "Barisal",
    "Chittagong",
    "Dhaka",
    "Khulna",
    "Rajshahi",
    "Rangpur",
    "Sylhet"
  ],
  "Barbados": [
    "Christ Church",
    "St. Andrew",
    "St. George",
    "St. James",
    "St. John",
    "St. Joseph",
    "St. Lucy",
    "St. Michael",
    "St. Peter",
    "St. Phillip",
    "St. Tomas"
  ],
  "Bassas da India": [
    "Administrative unit not available"
  ],
  "Belarus": [
    "Brest",
    "Gomel",
    "Grodno",
    "Minsk",
    "Minsk City",
    "Mogilev",
    "Vitebsk"
  ],
  "Belgium": [
    "Region de Bruxelles-Capitale / Brussels Hoofdstedelijk Gewes",
    "Region wallonne",
    "Vlaams Gewest"
  ],
  "Belize": [
    "Belize",
    "Cayo",
    "Corozal",
    "Orange Walk",
    "Stann Creek",
    "Toledo"
  ],
  "Benin": [
    "Alibori",
    "Atakora",
    "Atlantique",
    "Borgou",
    "Collines",
    "Couffo",
    "Donga",
    "Littoral",
    "Mono",
    "Oueme",
    "Plateau",
    "Zou"
  ],
  "Bermuda": [
    "Administrative unit not available"
  ],
  "Bhutan": [
    "Bumthang",
    "Chhukha",
    "Dagana",
    "Gasa",
    "Haa",
    "Lhuentse",
    "Monggar",
    "Paro",
    "Pemagatshel",
    "Punakha",
    "Samdrupjongkhar",
    "Samtse",
    "Sarpang",
    "Thimphu",
    "Trashigang",
    "Trashiyangtse",
    "Trongsa",
    "Tsirang",
    "Wangduephodrang",
    "Zhemgang"
  ],
  "Bird Island": [
    "Administrative unit not available"
  ],
  "Bolivia": [
    "Beni",
    "Chuquisaca",
    "Cochabamba",
    "La Paz",
    "Oruro",
    "Pando",
    "Potosi",
    "Santa Cruz",
    "Tarija"
  ],
  "Bosnia and Herzegovina": [
    "Federacija Bosne I Hercegovine",
    "Republika Srpska"
  ],
  "Botswana": [
    "Central",
    "Chobe",
    "Ghanzi",
    "Kgalagadi",
    "Kgatleng",
    "Kweneng",
    "Ngamiland",
    "North East",
    "South-East",
    "Southern"
  ],
  "Bouvet Island": [
    "Administrative unit not available"
  ],
  "Brazil": [
    "Acre",
    "Alagoas",
    "Amapa",
    "Amazonas",
    "Bahia",
    "Ceara",
    "Distrito Federal",
    "Espirito Santo",
    "Goias",
    "Maranhao",
    "Mato Grosso",
    "Mato Grosso Do Sul",
    "Minas Gerais",
    "Name Unknown",
    "Para",
    "Paraiba",
    "Parana",
    "Pernambuco",
    "Piaui",
    "Rio De Janeiro",
    "Rio Grande Do Norte",
    "Rio Grande Do Sul",
    "Rondonia",
    "Roraima",
    "Santa Catarina",
    "Sao Paulo",
    "Sergipe",
    "Tocantins"
  ],
  "British Indian Ocean Territory": [
    "Administrative unit not available"
  ],
  "British Virgin Islands": [
    "Anegada",
    "Jost van Dyke",
    "Other Islands",
    "Tortola",
    "Virgin Gorda"
  ],
  "Brunei Darussalam": [
    "Belait",
    "Brunei and Muara",
    "Temburong",
    "Tutong"
  ],
  "Bulgaria": [
    "Blagoevgrad",
    "Burgas",
    "Dobrich",
    "Gabrovo",
    "Haskovo",
    "Jambol",
    "Kardzhali",
    "Kustendil",
    "Lovech",
    "Montana",
    "Pazardzhik",
    "Pernik",
    "Pleven",
    "Plovdiv",
    "Razgrad",
    "Ruse",
    "Shumen",
    "Silistra",
    "Sliven",
    "Smoljan",
    "Sofia",
    "Sofia-city",
    "Stara Zagora",
    "Targovishte",
    "Varna",
    "Veliko Tarnovo",
    "Vidin",
    "Vratca"
  ],
  "Burkina Faso": [
    "Boucle Du Mouhoun",
    "Cascades",
    "Centre",
    "Centre-est",
    "Centre-nord",
    "Centre-ouest",
    "Centre-sud",
    "Est",
    "Hauts-bassins",
    "Nord",
    "Plateau Central",
    "Sahel",
    "Sud-ouest"
  ],
  "Burundi": [
    "Bubanza",
    "Bujumbura Mairie",
    "Bujumbura Rural",
    "Bururi",
    "Cankuzo",
    "Cibitoke",
    "Gitega",
    "Karuzi",
    "Kayanza",
    "Kirundo",
    "Makamba",
    "Muramvya",
    "Muyinga",
    "Mwaro",
    "Ngozi",
    "Rutana",
    "Ruyigi"
  ],
  "Cambodia": [
    "Area under National Administration 1",
    "Area under National Administration 2",
    "Banteay Meanchey",
    "Battambang",
    "Kampong Cham",
    "Kampong Chhnang",
    "Kampong Speu",
    "Kampong Thom",
    "Kampot",
    "Kandal",
    "Kep",
    "Koh Kong",
    "Kratie",
    "Mondul Kiri",
    "Otdar Meanchey",
    "Pailin",
    "Phnom Penh",
    "Preah Sihanouk",
    "Preah Vihear",
    "Prey Veng",
    "Pursat",
    "Ratanak Kiri",
    "Siem Reap",
    "Stung Treng",
    "Svay Rieng",
    "Takeo"
  ],
  "Cameroon": [
    "Adamaoua",
    "Centre",
    "Est",
    "Extr�me - Nord",
    "Littoral",
    "Nord",
    "Nord - Ouest",
    "Ouest",
    "Sud",
    "Sud - Ouest"
  ],
  "Canada": [
    "Alberta",
    "British Columbia / Colombie-Britannique",
    "Manitoba",
    "New Brunswick / Nouveau-Brunswick",
    "Newfoundland and Labrador / Terre-Neuve-et-Labrador",
    "Northwest Territories / Territoires du Nord-Ouest",
    "Nova Scotia / Nouvelle-�cosse",
    "Nunavut",
    "Ontario",
    "Prince Edward Island / �le-du-Prince-�douard",
    "Quebec / Qu�bec",
    "Saskatchewan",
    "Yukon"
  ],
  "Cape Verde": [
    "Boa Vista",
    "Brava",
    "Cima",
    "Fogo",
    "Ilheu Branco",
    "Ilheu Raso",
    "Maio",
    "Rombo",
    "Sal",
    "Santa Luzia",
    "Santiago",
    "Santo Antao",
    "Sao Nicolau",
    "Sao Vicente"
  ],
  "Cayman Islands": [
    "Cayman Brac",
    "Grand Cayman",
    "Little Cayman"
  ],
  "Central African Republic": [
    "Bamingui-Bangoran",
    "Bangui",
    "Basse-Kotto",
    "Haut-Mbomou",
    "Haute-Kotto",
    "K�mo",
    "Lobaye",
    "Mamb�r�-Kad��",
    "Mbomou",
    "Nana-Gribizi",
    "Nana-Mamb�r�",
    "Ombella M'Poko",
    "Ouaka",
    "Ouham",
    "Ouham Pend�",
    "Sangha-Mba�r�",
    "Vakaga"
  ],
  "Chad": [
    "Assongha",
    "Baguirmi",
    "Barh Koh",
    "Barl El Gazal",
    "Batha Est",
    "Batha Ouest",
    "Biltine",
    "Borkou",
    "Daraba",
    "Ennedi",
    "Guera",
    "Hadjer Lamis",
    "Kabia",
    "Kanem",
    "Lac",
    "Lac Iro",
    "Logone Occidental",
    "Logone Oriental",
    "Mandoul",
    "Mayo-Boneye",
    "Mayo-Dala",
    "Mont De Lam",
    "Ouaddai",
    "Salamat",
    "Sila",
    "Tandjile Est",
    "Tandjile Ouest",
    "Tibesti"
  ],
  "Chile": [
    "Aisen del Gral. Carlos Iba�ez del Campo",
    "Antofagasta",
    "Araucania",
    "Arica y Painacota",
    "Atacama",
    "Biobio",
    "Coquimbo",
    "Libertador Gral. Bernardo O'Higgins",
    "Los Lagos",
    "Los Rios",
    "Magallanes y Antartica chilena",
    "Maule",
    "Metropolitana",
    "Tarapaca",
    "Valparaiso"
  ],
  "China": [
    "Anhui Sheng",
    "Beijing Shi",
    "Chongqing Shi",
    "Fujian Sheng",
    "Gansu Sheng",
    "Guangdong Sheng",
    "Guangxi Zhuangzu Zizhiqu",
    "Guizhou Sheng",
    "Hainan Sheng",
    "Hebei Sheng",
    "Heilongjiang Sheng",
    "Henan Sheng",
    "Hubei Sheng",
    "Hunan Sheng",
    "Jiangsu Sheng",
    "Jiangxi Sheng",
    "Jilin Sheng",
    "Liaoning Sheng",
    "Nei Mongol Zizhiqu",
    "Ningxia Huizu Zizhiqu",
    "Qinghai Sheng",
    "Shaanxi Sheng",
    "Shandong Sheng",
    "Shanghai Shi",
    "Shanxi Sheng",
    "Sichuan Sheng",
    "Tianjin Shi",
    "Xinjiang Uygur Zizhiqu",
    "Xizang Zizhiqu",
    "Yunnan Sheng",
    "Zhejiang Sheng"
  ],
  "China/India": [
    "Administrative unit not available"
  ],
  "Christmas Island": [
    "Administrative unit not available"
  ],
  "Clipperton Island": [
    "Administrative unit not available"
  ],
  "Cocos (Keeling) Islands": [
    "Administrative unit not available"
  ],
  "Colombia": [
    "Amazonas",
    "Antioquia",
    "Arauca",
    "Atlantico",
    "Bolivar",
    "Boyaca",
    "Buenaventura",
    "Caldas",
    "Caqueta",
    "Casanare",
    "Cauca",
    "Cesar",
    "Choco",
    "Cordoba",
    "Cundinamarca",
    "Guainia",
    "Guajira",
    "Guaviare",
    "Huila",
    "Magdalena",
    "Meta",
    "Narino",
    "Norte De Santander",
    "Putumayo",
    "Quindio",
    "Risaralda",
    "San Andres Y Providencia",
    "Santander",
    "Sucre",
    "Tolima",
    "Valle Del Cauca",
    "Vaupes",
    "Vichada"
  ],
  "Comoros": [
    "Anjouan",
    "Moheli",
    "Ngazidja"
  ],
  "Congo": [
    "Bouenza",
    "Brazzaville",
    "Cuvette",
    "Cuvette-Ouest",
    "Kouilou",
    "Lekoumou",
    "Likouala",
    "Niari",
    "Plateaux",
    "Point-Noire",
    "Pool",
    "Sangha"
  ],
  "Cook Islands": [
    "Administrative unit not available"
  ],
  "Costa Rica": [
    "Alajuela",
    "Cartago",
    "Guanacaste",
    "Heredia",
    "Limon",
    "Puntarenas",
    "San Jose"
  ],
  "Croatia": [
    "Bjelovar-bilogora",
    "Dubrovnik-neretva",
    "Grad Zagreb",
    "Istra",
    "Karlovac",
    "Koprivnica-krizevci",
    "Krapina-zagorje",
    "Lika-senj",
    "Medimurje",
    "Osijek-baranja",
    "Pozega-slavonija",
    "Primorje-gorski Kota",
    "Sibenik",
    "Sisak-moslavina",
    "Slavonski Brod-posav",
    "Split-dalmatija",
    "Varazdin",
    "Virovitica-podravina",
    "Vukovar-srijem",
    "Zadar-knin",
    "Zagreb"
  ],
  "Cuba": [
    "Camaguey",
    "Ciego De Avila",
    "Cienfuegos",
    "Ciudad De La Habana",
    "Granma",
    "Guantanamo",
    "Holguin",
    "Isla De La Juventud",
    "La Habana",
    "Las Tunas",
    "Matanzas",
    "Pinar Del Rio",
    "Sancti Spiritus",
    "Santiago De Cuba",
    "Villa Clara"
  ],
  "Cyprus": [
    "Famgusta",
    "Kyrenia",
    "Larnaca",
    "Limassol",
    "Nicosia",
    "Paphos"
  ],
  "Czech Republic": [
    "Jihocesky",
    "Jihomoravsky",
    "Praha",
    "Severocesky",
    "Severomoravsky",
    "Stredocesky",
    "Vychodocesky",
    "Zapadocesky"
  ],
  "C�te d'Ivoire": [
    "Bas Sassandra",
    "Comoe",
    "Denguele",
    "District autonome de Abidjan",
    "District autonome de Yamoussoukro",
    "G�h-Djiboua",
    "Lacs",
    "Lagunes",
    "Montagnes",
    "Sassandra-Marahoue",
    "Savanes",
    "Vallee Du Bandama",
    "Woroba",
    "Zanzan"
  ],
  "Dem People's Rep of Korea": [
    "Chagang-do",
    "Hamgyong-bukto",
    "Hamgyong-namdo",
    "Hwanghae-bukto",
    "Hwanghae-namdo",
    "Kaesong-si",
    "Kangwon-do",
    "P'yongan-bukto",
    "P'yongan-namdo",
    "P'yongyang-si",
    "Yanggang-do"
  ],
  "Democratic Republic of the Congo": [
    "Bandundu",
    "Bas-Congo",
    "Equateur",
    "Kasai Occidental",
    "Kasai Oriental",
    "Katanga",
    "Kinshasa",
    "Maniema",
    "Nord-Kivu",
    "Orientale",
    "Sud-Kivu"
  ],
  "Denmark": [
    "Aarhus",
    "Bornholm",
    "Frederiksberg",
    "Frederiksborg",
    "Fyn",
    "Koebenhavn",
    "Nordjylland",
    "Ribe",
    "Ringkoebing",
    "Roskilde",
    "Soenderjylland",
    "Storstroem",
    "Vejle",
    "Vestsjaelland",
    "Viborg"
  ],
  "Djibouti": [
    "Ali Sabieh",
    "Dikhil",
    "Djibouti",
    "Obock",
    "Tadjourah"
  ],
  "Dominica": [
    "St. Andrew",
    "St. David",
    "St. George",
    "St. John",
    "St. Joseph",
    "St. Luke",
    "St. Mark",
    "St. Patrick",
    "St. Paul",
    "St. Peter"
  ],
  "Dominican Republic": [
    "Azua",
    "Baoruco",
    "Barahona",
    "Dajabon",
    "Distrito Nacional",
    "Duarte",
    "El Seibo",
    "Elias Pina",
    "Espaillat",
    "Hato Mayor",
    "Independencia",
    "La Altagracia",
    "La Romana",
    "La Vega",
    "Maria Trinidad Sanches",
    "Monsenor Nouel",
    "Monte Cristi",
    "Monte Plata",
    "Pedernales",
    "Peravia",
    "Puerto Plata",
    "Salcedo",
    "Samana",
    "San Cristobal",
    "San Jos� de Ocoa",
    "San Juan",
    "San Pedro de Macoris",
    "Sanchez Ramirez",
    "Santiago",
    "Santiago Rodriguez",
    "Santo Domingo",
    "Valverde"
  ],
  "Ecuador": [
    "Azuay",
    "Bolivar",
    "Canar",
    "Carchi",
    "Chimborazo",
    "Cotopaxi",
    "El Oro",
    "Esmeraldas",
    "Galapagos",
    "Guayas",
    "Imbabura",
    "Loja",
    "Los Rios",
    "Manabi",
    "Morona Santiago",
    "Napo",
    "Orellana",
    "Pastaza",
    "Pichincha",
    "Santa Elena",
    "Santo Domingo de los Tsachilas",
    "Sucumbios",
    "Tungurahua",
    "Zamora Chinchipe",
    "Zona No Delimitada"
  ],
  "Egypt": [
    "Alexandria",
    "Assiut",
    "Aswan",
    "Behera",
    "Beni Suef",
    "Cairo",
    "Dakahlia",
    "Damietta",
    "Fayoum",
    "Gharbia",
    "Giza",
    "Ismailia",
    "Kafr El-Shikh",
    "Kalyoubia",
    "Luxor",
    "Matrouh",
    "Menia",
    "Menoufia",
    "New Valley",
    "North Sinai",
    "Port Said",
    "Qena",
    "Red Sea",
    "Shrkia",
    "South Sinai",
    "Suez",
    "Suhag"
  ],
  "El Salvador": [
    "Ahuachapan",
    "Cabanas",
    "Chalatenango",
    "Cuscatlan",
    "La Libertad",
    "La Paz",
    "La Union",
    "Morazan",
    "San Miguel",
    "San Salvador",
    "San Vicente",
    "Santa Ana",
    "Sonsonate",
    "Usulutan"
  ],
  "Equatorial Guinea": [
    "Annobon",
    "Bioko Norte",
    "Bioko Sur",
    "Centro Sur",
    "Kientem",
    "Litoral",
    "Welenzas"
  ],
  "Eritrea": [
    "Anseba",
    "Archipelagos",
    "Debub",
    "Debubawi Keih Bahri",
    "Gash Barka",
    "Maekel",
    "Semenawi Keih Bahri"
  ],
  "Estonia": [
    "Administrative unit not available",
    "Harju maakond",
    "Hiiu maakond",
    "Ida-Viru maakond",
    "J�geva maakond",
    "J�rva maakond",
    "L��ne maakond",
    "L��ne-Viru maakond",
    "P�lva maakond",
    "P�rnu maakond",
    "Rapla maakond",
    "Saare maakond",
    "Tartu maakond",
    "Valga maakond",
    "Viljandi maakond",
    "V�ru maakond"
  ],
  "Ethiopia": [
    "Addis Ababa",
    "Afar",
    "Amhara",
    "Beneshangul Gumu",
    "Dire Dawa",
    "Gambela",
    "Hareri",
    "Oromia",
    "SNNPR",
    "Somali",
    "Tigray"
  ],
  "Europa Island": [
    "Administrative unit not available"
  ],
  "Falkland Islands (Malvinas)": [
    "Administrative unit not available"
  ],
  "Faroe Islands": [
    "Administrative unit not available"
  ],
  "Fiji": [
    "Central",
    "Eastern",
    "Northern",
    "Western"
  ],
  "Finland": [
    "Aaland",
    "Eastern Finland",
    "Lapland",
    "Oulu",
    "Southern Finland",
    "Western Finland"
  ],
  "France": [
    "Alsace",
    "Aquitaine",
    "Auvergne",
    "Basse-Normandie",
    "Bourgogne",
    "Bretagne",
    "Centre",
    "Champagne-Ardenne",
    "Corse",
    "Franche-Comte",
    "Haute-Normandie",
    "Ile-de-France",
    "Languedoc-Rousillon",
    "Limousin",
    "Lorraine",
    "Midi-Pyrenees",
    "Nord-Pas-de-Calais",
    "Pays-de-la-Loire",
    "Picardie",
    "Poitou-Charentes",
    "Provence-Alpes-Cote-d'Azur",
    "Rhone-Alpes"
  ],
  "French Guiana": [
    "Cayenne",
    "Saint-laurent-du-maroni"
  ],
  "French Polynesia": [
    "Administrative unit not available"
  ],
  "French Southern and Antarctic Territories": [
    "Administrative unit not available"
  ],
  "Gabon": [
    "Estuaire",
    "Haut-Ogooue",
    "Moyen-Ogooue",
    "Ngounie",
    "Nyanga",
    "Ogooue-Ivindo",
    "Ogooue-Maritime",
    "Ogooue-lolo",
    "Woleu-Ntem"
  ],
  "Gambia": [
    "Central River",
    "Kanifing Municipal Council",
    "Lower River",
    "North Bank",
    "Upper River",
    "West Coast"
  ],
  "Gaza Strip": [
    "Deir al Balah",
    "Gaza",
    "Jabalya",
    "Khan Yunis",
    "Rafah"
  ],
  "Georgia": [
    "Abkhazia Aut. Rep.",
    "Adjara Aut. Rep.",
    "Guria",
    "Imereti",
    "Kakheti",
    "Kvemo Kartli",
    "Mtskheta-Mtianeti",
    "Racha-Lechkhumi and Kvemo (lower) Svaneti",
    "Samergelo and Zemo (upper) Svaneti",
    "Samtskhe-Javakheti",
    "Shida Kartli",
    "Tbilisi"
  ],
  "Germany": [
    "Baden-Wuerttemberg",
    "Bayern",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hessen",
    "Mecklenburg-Vorpommern",
    "Niedersachsen",
    "Nordrhein-Westfalen",
    "Rheinland-Pfalz",
    "Saarland",
    "Sachsen",
    "Sachsen-Anhalt",
    "Schleswig-Holstein",
    "Thueringen"
  ],
  "Ghana": [
    "Ashanti",
    "Brong Ahafo",
    "Central",
    "Eastern",
    "Greater Accra",
    "Northern",
    "Upper East",
    "Upper West",
    "Volta",
    "Western"
  ],
  "Gibraltar": [
    "Administrative unit not available"
  ],
  "Glorioso Island": [
    "Administrative unit not available"
  ],
  "Greece": [
    "Anatoliki Makedonia Kai Thraki",
    "Attiki",
    "Dytiki Ellada",
    "Dytiki Makedonia",
    "Ionioi Nisoi",
    "Ipeiros",
    "Kentriki Makedonia",
    "Kriti",
    "Notio Aigaio",
    "Peloponnisos",
    "Sterea Ellada",
    "Thessalia",
    "Voreio Aigaio"
  ],
  "Greenland": [
    "Nordgronland",
    "Ostgronland",
    "Vestgronland"
  ],
  "Grenada": [
    "Name Unknown",
    "St. Andrew's",
    "St. George's",
    "St. John's",
    "St. Mark's",
    "St. Patrick's"
  ],
  "Guadeloupe": [
    "Administrative unit not available"
  ],
  "Guam": [
    "Administrative unit not available"
  ],
  "Guatemala": [
    "Alta Verapaz",
    "Baja Verapaz",
    "Chimaltenango",
    "Chiquimula",
    "El Progreso",
    "Escuintla",
    "Guatemala",
    "Huehuetenango",
    "Izabal",
    "Jalapa",
    "Jutiapa",
    "Pet�n",
    "Quetzaltenango",
    "Quich�",
    "Retalhuleu",
    "Sacatep�quez",
    "San Marcos",
    "Santa Rosa",
    "Solol�",
    "Suchitep�quez",
    "Totonicap�n",
    "Zacapa"
  ],
  "Guernsey": [
    "Alderney",
    "Castel",
    "Forest",
    "Herm",
    "Saint Andrew",
    "Saint Martin",
    "Saint Peter",
    "Saint Peter Port",
    "Saint Sampson",
    "Saint Saviour",
    "Sark",
    "Torteval",
    "Vale"
  ],
  "Guinea": [
    "Boke",
    "Conakry",
    "Faranah",
    "Kankan",
    "Kindia",
    "Labe",
    "Mamou",
    "Nzerekore"
  ],
  "Guinea-Bissau": [
    "Bafata",
    "Biombo",
    "Bolama/bijagos",
    "Cacheu",
    "Gabu",
    "Oio",
    "Quinara",
    "Sector Autonomo De Bissau",
    "Tombali"
  ],
  "Guyana": [
    "Barima Waini (region N�1)",
    "Cuyuni/mazaruni (region N�7)",
    "Demerara Mahaica (region N�4)",
    "East Berbice/corentyne (region N�6)",
    "Essequibo Islands/west Demerara (region N�3)",
    "Mahaica Berbice (region N�5)",
    "Pomeroon/supenaam (region N�2",
    "Potaro/siparuni (region N�8)",
    "Upper Demerara/berbice (region N�10)",
    "Upper Takutu/upper Essequibo (region N�9)"
  ],
  "Haiti": [
    "Artibonite",
    "Centre",
    "Grande Anse",
    "Nippes",
    "Nord",
    "Nord Est",
    "Nord Ouest",
    "Ouest",
    "Sud",
    "Sud Est"
  ],
  "Hala'ib triangle": [
    "Administrative unit not available"
  ],
  "Heard Island and McDonald Islands": [
    "Administrative unit not available"
  ],
  "Holy See": [
    "Administrative unit not available"
  ],
  "Honduras": [
    "Atlantida",
    "Choluteca",
    "Colon",
    "Comayagua",
    "Copan",
    "Cortes",
    "Francisco Morazan",
    "Gracias A Dios",
    "Intibuca",
    "Islas De Bahia",
    "La Paz",
    "Lempira",
    "Name Unknown",
    "Ocotepeque",
    "Olancho",
    "Paraiso",
    "Santa Barbara",
    "Valle",
    "Yoro"
  ],
  "Hong Kong": [
    "Administrative unit not available"
  ],
  "Howland Island": [
    "Administrative unit not available"
  ],
  "Hungary": [
    "Bacs-kiskun",
    "Baranya",
    "Bekes",
    "Borsod-abauj-zemplen",
    "Budapest",
    "Csongrad",
    "Fejer",
    "Gyor-moson-sopron",
    "Hajdu-bihar",
    "Heves",
    "Jasz-nagykun-szolnok",
    "Komarom-esztergom",
    "Nograd",
    "Pest",
    "Somogy",
    "Szabolcs-szatmar-bereg",
    "Tolna",
    "Vas",
    "Veszprem",
    "Zala"
  ],
  "Iceland": [
    "Arnes",
    "Austur-baroastrandar",
    "Austur-hunavatns",
    "Austur-skaftafells",
    "Borgarfjaroar",
    "Dala",
    "Eyjafjaroar",
    "Gullbringu",
    "Kjosar",
    "Myra",
    "Nordhurland Eystra",
    "Norour-isafjaroar",
    "Norour-m�la",
    "Norour-pingeyjar",
    "Rang�rvalla",
    "Skagafjaroar",
    "Snaefellsnes- Og Hna",
    "Stranda",
    "Suour-m�la",
    "Suour-pingeyjar",
    "Vestur-baroastrandar",
    "Vestur-hunavatns",
    "Vestur-isafjaroar",
    "Vestur-skaftafells"
  ],
  "Ilemi triangle": [
    "Administrative unit not available"
  ],
  "India": [
    "Andaman and Nicobar",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli",
    "Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Orissa",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal"
  ],
  "Indonesia": [
    "Bali",
    "Bangka Belitung",
    "Banten",
    "Bengkulu",
    "Daerah Istimewa Yogyakarta",
    "Dki Jakarta",
    "Gorontalo",
    "Jambi",
    "Jawa Barat",
    "Jawa Tengah",
    "Jawa Timur",
    "Kalimantan Barat",
    "Kalimantan Selatan",
    "Kalimantan Tengah",
    "Kalimantan Timur",
    "Kepulauan-riau",
    "Lampung",
    "Maluku",
    "Maluku Utara",
    "Nangroe Aceh Darussalam",
    "Nusatenggara Barat",
    "Nusatenggara Timur",
    "Papua",
    "Papua Barat",
    "Riau",
    "Sulawesi Barat",
    "Sulawesi Selatan",
    "Sulawesi Tengah",
    "Sulawesi Tenggara",
    "Sulawesi Utara",
    "Sumatera Barat",
    "Sumatera Selatan",
    "Sumatera Utara"
  ],
  "Iran  (Islamic Republic of)": [
    "Administrative unit not available",
    "Ardebil",
    "Bushehr",
    "Chaharmahal-o bakhtiyar",
    "East Azarbayejan",
    "Esfahan",
    "Fars",
    "Ghazvin",
    "Ghom",
    "Gilan",
    "Golestan",
    "Hamedan",
    "Hormozgan",
    "Ilam",
    "Kerman",
    "Kermanshah",
    "Khorasan",
    "Khuzestan",
    "Kohgiluyeh va boyerahma",
    "Kordestan",
    "Lorestan",
    "Markazi",
    "Mazandaran",
    "Semnan",
    "Sistan-o baluchestan",
    "Tehran",
    "West Azarbayejan",
    "Yazd",
    "Zanjan"
  ],
  "Iraq": [
    "Anbar",
    "Babil",
    "Baghdad",
    "Basrah",
    "Dahuk",
    "Diyala",
    "Erbil",
    "Kerbala",
    "Kirkuk",
    "Missan",
    "Muthanna",
    "Najaf",
    "Ninewa",
    "Qadissiya",
    "Salah al-Din",
    "Sulaymaniyah",
    "Thi-Qar",
    "Wassit"
  ],
  "Ireland": [
    "Carlow",
    "Cavan",
    "Clare",
    "Cork",
    "Donegal",
    "Dublin",
    "Galway",
    "Kerry",
    "Kildare",
    "Kilkenny",
    "Laois",
    "Leitrim",
    "Limerick",
    "Longford",
    "Louth",
    "Mayo",
    "Meath",
    "Monaghan",
    "Munster",
    "Offaly",
    "Roscommon",
    "Sligo",
    "Tipperary",
    "Waterford",
    "Westmeath",
    "Wexford",
    "Wicklow"
  ],
  "Isle of Man": [
    "Andreas",
    "Arbory",
    "Ballaugh",
    "Braddan",
    "Bride",
    "Castletown",
    "Douglas",
    "German",
    "Jurby",
    "Laxey",
    "Lezayre",
    "Lonan",
    "Malew",
    "Marown",
    "Maughold",
    "Michael",
    "Onchan",
    "Patrick",
    "Peel",
    "Port Erin",
    "Port St.Mary",
    "Ramsey",
    "Rushen",
    "Santan"
  ],
  "Israel": [
    "Central District",
    "Haifa",
    "Jerusalem",
    "Northern",
    "Southern District",
    "Tel Aviv"
  ],
  "Italy": [
    "Abruzzi",
    "Basilicata",
    "Calabria",
    "Campania",
    "Emilia-romagna",
    "Friuli-venezia Giulia",
    "Lazio",
    "Liguria",
    "Lombardia",
    "Marche",
    "Molise",
    "Piemonte",
    "Puglia",
    "Sardegna",
    "Sicilia",
    "Toscana",
    "Trentino-alto Adige",
    "Umbria",
    "Valle D'aosta",
    "Veneto"
  ],
  "Jamaica": [
    "Clarendon",
    "Hanover",
    "Manchester",
    "Portland",
    "Saint Andrew And Kingston",
    "Saint Ann",
    "Saint Catherine",
    "Saint Elizabeth",
    "Saint James",
    "Saint Mary",
    "Saint Thomas",
    "Trelawny",
    "Westmoreland"
  ],
  "Jammu and Kashmir": [
    "Administrative unit not available"
  ],
  "Japan": [
    "Aiti",
    "Akita",
    "Aomori",
    "Ehime",
    "Gifu",
    "Gunma",
    "Hirosima",
    "Hokkaidoo",
    "Hukui",
    "Hukuoka",
    "Hukusima",
    "Hyoogo",
    "Ibaraki",
    "Isikawa",
    "Iwate",
    "Kagawa",
    "Kagosima",
    "Kanagawa",
    "Kooti",
    "Kumamoto",
    "Kyooto",
    "Mie",
    "Miyagi",
    "Miyazaki",
    "Nagano",
    "Nagasaki",
    "Nara",
    "Niigata",
    "Okayama",
    "Okinawa",
    "Ooita",
    "Oosaka",
    "Saga",
    "Saitama",
    "Siga",
    "Simane",
    "Sizuoka",
    "Tiba",
    "Tokusima",
    "Tookyoo",
    "Totigi",
    "Tottori",
    "Toyama",
    "Wakayama",
    "Yamagata",
    "Yamaguti",
    "Yamanasi"
  ],
  "Jarvis Island": [
    "Administrative unit not available"
  ],
  "Jersey": [
    "Brelade",
    "Grouville",
    "Saint Clement",
    "Saint Helier",
    "Saint John",
    "Saint Lawrence",
    "Saint Martin",
    "Saint Mary",
    "Saint Ouen",
    "Saint Peter",
    "Saint Saviour",
    "Trinity"
  ],
  "Johnston Atoll": [
    "Administrative unit not available"
  ],
  "Jordan": [
    "Ajloon",
    "Amman",
    "Aqaba",
    "Balqa",
    "Irbid",
    "Jarash",
    "Karak",
    "Ma'an",
    "Madaba",
    "Mafraq",
    "Tafiela",
    "Zarqa"
  ],
  "Juan de Nova Island": [
    "Administrative unit not available"
  ],
  "Kazakhstan": [
    "Administrative unit not available",
    "Akmolinskaya",
    "Aktyubinskaya",
    "Almatinskaya",
    "Almaty City area",
    "Atyrauskaya",
    "Jambylslkaya",
    "Karagandinskaya",
    "Kustanayskaya",
    "Kyzylordinskaya",
    "Mangistauskaya",
    "Pavlodarskaya",
    "Severo-kazachstanskaya",
    "Vostochno-kazachstanskaya",
    "Yujno-kazachstanskaya",
    "Zapadno-kazachstanskaya"
  ],
  "Kenya": [
    "Central",
    "Coast",
    "Eastern",
    "Nairobi",
    "North Eastern",
    "Nyanza",
    "Rift Valley",
    "Western"
  ],
  "Kingman Reef": [
    "Administrative unit not available"
  ],
  "Kiribati": [
    "Administrative unit not available"
  ],
  "Kuril islands": [
    "Administrative unit not available"
  ],
  "Kuwait": [
    "Al Ahmadi",
    "Al Farwaniyah",
    "Al Jahrah",
    "Al Kuwayt",
    "Hawalli"
  ],
  "Kyrgyzstan": [
    "Batken",
    "Chuy",
    "Jalal-Abad",
    "Naryn",
    "Osh",
    "Talas",
    "Ysyk-Kol"
  ],
  "Lao People's Democratic Republic": [
    "Attapu",
    "Bokeo",
    "Bolikhamxai",
    "Champasak",
    "Houaphan",
    "Khammouan",
    "Louang-Namtha",
    "Louangphabang",
    "Oudomxai",
    "Phongsali",
    "Salavan",
    "Savannakhet",
    "Vientiane",
    "Vientiane capital",
    "Xaignabouli",
    "Xekong",
    "Xiangkhouang"
  ],
  "Latvia": [
    "Aizkraukles",
    "Aluksnes",
    "Balvu",
    "Bauskas",
    "Cesu",
    "Daugavpils",
    "Dobeles",
    "Gulbenes",
    "Jekabpils",
    "Jelgavas",
    "Kraslavas",
    "Kuldigas",
    "Liepajas",
    "Limbazu",
    "Ludzas",
    "Madonas",
    "Ogres",
    "Preilu",
    "Rezeknes",
    "Rigas",
    "Saldus",
    "Talsu",
    "Tukuma",
    "Valkas",
    "Valmieras",
    "Ventspils"
  ],
  "Lebanon": [
    "Beirut",
    "Bekaa",
    "Mount Lebanon",
    "Nabatiye",
    "North",
    "South"
  ],
  "Lesotho": [
    "Berea",
    "Butha Buthe",
    "Leribe",
    "Mafeteng",
    "Maseru",
    "Mohale's Hoek",
    "Mokhotlong",
    "Qacha's Nek",
    "Quthing",
    "Thaba Tseka"
  ],
  "Liberia": [
    "Bomi",
    "Bong",
    "Gbarpolu",
    "Grand Bassa",
    "Grand Cape Mount",
    "Grand Gedeh",
    "Grand Kru",
    "Lofa",
    "Margibi",
    "Maryland",
    "Montserrado",
    "Nimba",
    "River Gee",
    "Rivercess",
    "Sinoe"
  ],
  "Libya": [
    "Ajdabiya (agedabia)",
    "Al Aziziyah",
    "Al Fatah",
    "Al Jabal Al Akhdar",
    "Al Jufrah",
    "Al Khoms",
    "Al Kufrah",
    "Ash Shati",
    "Awbari (ubari)",
    "Az Zawia (azzawiya)",
    "Banghazi",
    "Darnah",
    "Ghadamis",
    "Gharyan",
    "Misurata",
    "Murzuq",
    "Nuqat Al Khams",
    "Sabha",
    "Sawfajjin (sofuljeen)",
    "Surt (sirte)",
    "Tarhunah",
    "Tripoli (tarabulus)",
    "Tubruq (tobruk)",
    "Yafran (yefren)",
    "Zeleitin (zliten)"
  ],
  "Liechtenstein": [
    "Balzers",
    "Eschen",
    "Gamprin",
    "Mauren",
    "Planken",
    "Ruggell",
    "Schaan",
    "Schellenberg",
    "Triesen",
    "Triesenberg",
    "Vaduz"
  ],
  "Lithuania": [
    "Alytaus",
    "Kauno",
    "Klaipedos",
    "Marijampoles",
    "Panevezio",
    "Siauliu",
    "Taurages",
    "Telsiu",
    "Utenos",
    "Vilniaus"
  ],
  "Luxembourg": [
    "Diekirch",
    "Grevenmacher",
    "Luxembourg"
  ],
  "Ma'tan al-Sarra": [
    "Administrative unit not available"
  ],
  "Macau": [
    "Administrative unit not available"
  ],
  "Madagascar": [
    "Alaotra Mangoro",
    "Amoron I Mania",
    "Analamanga",
    "Analanjirofo",
    "Androy",
    "Anosy",
    "Atsimo Andrefana",
    "Atsimo Atsinanana",
    "Atsinanana",
    "Betsiboka",
    "Boeny",
    "Bongolava",
    "Diana",
    "Haute Matsiatra",
    "Ihorombe",
    "Itasy",
    "Melaky",
    "Menabe",
    "Sava",
    "Sofia",
    "Vakinankaratra",
    "Vatovavy Fitovinany"
  ],
  "Madeira Islands": [
    "Ilha Da Madeira (madeira)",
    "Ilha De Porto Santo (madeira)"
  ],
  "Malawi": [
    "Area under National Administration",
    "Central Region",
    "Northern Region",
    "Southern Region"
  ],
  "Malaysia": [
    "Johor",
    "Kedah",
    "Kelantan",
    "Kuala Lumpur",
    "Labuan",
    "Melaka",
    "Negeri Sembilan",
    "Pahang",
    "Perak",
    "Perlis",
    "Pulau Pinang",
    "Sabah",
    "Sarawak",
    "Selangor",
    "Terengganu"
  ],
  "Maldives": [
    "Alifu Alifu",
    "Alifu Dhaalu",
    "Baa",
    "Dhaalu",
    "Faafu",
    "Gaafu Alifu",
    "Gaafu Dhaalu",
    "Haa Alifu",
    "Haa Dhaalu",
    "Kaafu",
    "Laamu",
    "Lhaviyani",
    "Male'",
    "Meemu",
    "Noonu",
    "Raa",
    "Seenu",
    "Shaviyani",
    "Thaa",
    "Vaavu"
  ],
  "Mali": [
    "Bamako",
    "Gao",
    "Kayes",
    "Kidal",
    "Koulikoro",
    "Mopti",
    "Segou",
    "Sikasso",
    "Tombouctou"
  ],
  "Malta": [
    "Attard",
    "Balzan",
    "Birgu",
    "Birkirkara",
    "Birzebbugia",
    "Bormla",
    "Dingli",
    "Fgura",
    "Floriana",
    "Fontana",
    "Ghajnsielem",
    "Gharb",
    "Gharghur",
    "Ghasri",
    "Ghaxaq",
    "Gudja",
    "Gzira",
    "Hamrun",
    "Iklin",
    "Isla",
    "Kalkara",
    "Kercem",
    "Kirkop",
    "Lija",
    "Luqa",
    "Marsa",
    "Marsascala",
    "Marsaxlokk",
    "Mdina",
    "Mellieha",
    "Mgarr",
    "Mosta",
    "Mqabba",
    "Msida",
    "Munxar",
    "Nadur",
    "Naxxar",
    "Paola",
    "Pembroke",
    "Pieta",
    "Qala",
    "Qormi",
    "Qrendi",
    "Rabat (malta)",
    "Rabat (victoria)",
    "Safi",
    "San Giljan",
    "San Gwann",
    "San Lawrenz",
    "San Pawl Ii-bahar",
    "Sannat",
    "Santa Lucija",
    "Santa Venera",
    "Siggiewi",
    "Sliema",
    "Swieqi",
    "Ta' Xbiex",
    "Tarxien",
    "Valletta",
    "Xaghra",
    "Xewkija",
    "Xghajra",
    "Zabbar",
    "Zebbug (gozo)",
    "Zebbug (malta)",
    "Zejtun",
    "Zurrieq"
  ],
  "Marshall Islands": [
    "Administrative unit not available"
  ],
  "Martinique": [
    "Fort-de-France",
    "La Trinite",
    "Le Marin",
    "Saint-Pierre"
  ],
  "Mauritania": [
    "Adrar",
    "Assaba",
    "Brakna",
    "Dakhlet-Nouadhibou",
    "Gorgol",
    "Guidimakha",
    "Hodh Ech Chargi",
    "Hodh El Gharbi",
    "Inchiri",
    "Nouakchott",
    "Tagant",
    "Tiris-Zemmour",
    "Trarza"
  ],
  "Mauritius": [
    "Administrative unit not available",
    "Black River",
    "Flacq",
    "Grand Port",
    "Moka",
    "Pamplemousses",
    "Plaines Wilhems",
    "Port Louis",
    "Riviere Du Rempart",
    "Savanne"
  ],
  "Mayotte": [
    "Administrative unit not available"
  ],
  "Mexico": [
    "Aguascalientes",
    "Baja California",
    "Baja California Sur",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Coahuila",
    "Colima",
    "Distrito Federal",
    "Durango",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "Mexico",
    "Michoacan",
    "Morelos",
    "Nayarit",
    "Nuevo Leon",
    "Oaxaca",
    "Puebla",
    "Queretaro",
    "Quintana Roo",
    "San Luis Potosi",
    "Sinaloa",
    "Sonora",
    "Tabasco",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz",
    "Yucatan",
    "Zacatecas"
  ],
  "Micronesia (Federated States of)": [
    "Administrative unit not available"
  ],
  "Midway Island": [
    "Administrative unit not available"
  ],
  "Moldova, Republic of": [
    "Balti",
    "Cahul",
    "Chisinau",
    "Dubasari",
    "Edinet",
    "Gagauzia",
    "Lapusna",
    "Orhei",
    "Soroca",
    "Tighina",
    "Ungheni"
  ],
  "Monaco": [
    "Administrative unit not available"
  ],
  "Mongolia": [
    "Arxangai",
    "Bayan-O'lgii",
    "Bayanxongor",
    "Bulgan",
    "Darxan-Uul",
    "Dornod",
    "Dornogovi",
    "Dundgovi",
    "Govi-Altai",
    "Govisu'mber",
    "O'mnogovi",
    "O'vorxangai",
    "Orxon",
    "Selenge",
    "Su'xbaatar",
    "To'v",
    "Ulaanbaatar",
    "Uvs",
    "Xentii",
    "Xo'vsgol",
    "Xovd",
    "Zavxan"
  ],
  "Montenegro": [
    "Andrijevica",
    "Bar",
    "Berane",
    "Bijelo Polje",
    "Budva",
    "Cetinje",
    "Danilovgrad",
    "Herceg Novi",
    "Kolasin",
    "Kotor",
    "Mojkovac",
    "Niksic",
    "Plav",
    "Pljevlja",
    "Pluzine",
    "Podgorica",
    "Rozaj",
    "Savnik",
    "Tivat",
    "Ulcinj",
    "Zabljak"
  ],
  "Montserrat": [
    "Brodericks",
    "Central",
    "East",
    "North",
    "Plymouth",
    "Salem",
    "South"
  ],
  "Morocco": [
    "Chaouia - Ouardigha",
    "Doukkala - Abda",
    "F�s - Boulemane",
    "Gharb - Chrarda - B�ni Hssen",
    "Grand Casablanca",
    "Guelmim - Es-Semara",
    "La�youne - Boujdour - Sakia El Hamra",
    "Marrakech - Tensift - Al Haouz",
    "Mekn�s - Tafilalet",
    "Oriental",
    "Rabat - Sal� - Zemmour - Zaer",
    "Souss - Massa - Dra�",
    "Tadla - Azilal",
    "Tanger - T�touan",
    "Taza - Al Hoceima - Taounate"
  ],
  "Mozambique": [
    "Cabo Delgado",
    "Gaza",
    "Inhambane",
    "Lago niassa",
    "Manica",
    "Maputo",
    "Nampula",
    "Niassa",
    "Sofala",
    "Tete",
    "Zambezia"
  ],
  "Myanmar": [
    "Ayeyawaddy",
    "Bago (E)",
    "Bago (W)",
    "Chin",
    "Kachin",
    "Kayar",
    "Kayin",
    "Magway",
    "Mandalay",
    "Mon",
    "Rakhine",
    "Sagaing",
    "Shan (E)",
    "Shan (N)",
    "Shan (S)",
    "Taninthayi",
    "Yangon"
  ],
  "Namibia": [
    "Caprivi",
    "Erongo",
    "Hardap",
    "Karas",
    "Kavango",
    "Khomas",
    "Kunene",
    "Ohangwena",
    "Omaheke",
    "Omusati",
    "Oshana",
    "Oshikoto",
    "Otjozondjupa"
  ],
  "Nauru": [
    "Administrative unit not available"
  ],
  "Navassa Island": [
    "Administrative unit not available"
  ],
  "Nepal": [
    "Central",
    "Eastern",
    "Far Western",
    "Mid Western",
    "Western"
  ],
  "Netherlands": [
    "Drenthe",
    "Flevoland",
    "Friesland",
    "Gelderland",
    "Groningen",
    "Limburg",
    "Noord-brabant",
    "Noord-holland",
    "Overijssel",
    "Utrecht",
    "Zeeland",
    "Zuid-holland"
  ],
  "Netherlands Antilles": [
    "Administrative unit not available"
  ],
  "New Caledonia": [
    "Administrative unit not available"
  ],
  "New Zealand": [
    "Auckland",
    "Bay Of Plenty",
    "Canterbury",
    "East Cape",
    "Hawke's Bay",
    "Nelson-marlborough",
    "Northland",
    "Otago",
    "Southland",
    "Taranaki",
    "Waikato",
    "Wanganui-manawatu",
    "Wellington",
    "Westland"
  ],
  "Nicaragua": [
    "Atlantico Norte",
    "Atlantico Sur",
    "Boaco",
    "Carazo",
    "Chinandega",
    "Chontales",
    "Esteli",
    "Granada",
    "Jinotega",
    "Leon",
    "Madriz",
    "Managua",
    "Masaya",
    "Matagalpa",
    "Nueva Segovia",
    "Rio San Juan",
    "Rivas"
  ],
  "Niger": [
    "Agadez",
    "Diffa",
    "Dosso",
    "Maradi",
    "Niamey",
    "Tahoua",
    "Tillaberi",
    "Zinder"
  ],
  "Nigeria": [
    "Abia",
    "Abuja",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nassarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara"
  ],
  "Niue": [
    "Administrative unit not available"
  ],
  "Norfolk Island": [
    "Administrative unit not available"
  ],
  "Northern Mariana Islands": [
    "Administrative unit not available"
  ],
  "Norway": [
    "Akershus",
    "Aust-agder",
    "Buskerud",
    "Finnmark",
    "Hedmark",
    "Hordaland",
    "Moere Og Romsdal",
    "Nord-troendelag",
    "Nordland",
    "Oestfold",
    "Oppland",
    "Oslo",
    "Rogaland",
    "Soer-Troendelag",
    "Sogn og Fjordane",
    "Telemark",
    "Troms",
    "Vest-Agder",
    "Vestfold"
  ],
  "Oman": [
    "A Dakhliya",
    "A Sharqiya",
    "Al Batnah",
    "Al Dhahira",
    "Al Wusta",
    "Dhofar",
    "Musandam",
    "Muscat",
    "Name Unknown"
  ],
  "Pakistan": [
    "Balochistan",
    "Federally Administered Tribal Areas",
    "Islamabad",
    "North-West Frontier",
    "Punjab",
    "Sindh"
  ],
  "Palau": [
    "Administrative unit not available"
  ],
  "Palmyra Atoll": [
    "Administrative unit not available"
  ],
  "Panama": [
    "Bocas del Toro",
    "Chiriqu�",
    "Cocl�",
    "Col�n",
    "Dari�n",
    "Ember�",
    "Herrera",
    "Kuna Yala",
    "Los Santos",
    "Ng�be Bugl�",
    "Panam�",
    "Veraguas"
  ],
  "Papua New Guinea": [
    "Central",
    "Chimbu",
    "East New Britain",
    "East Sepik",
    "Eastern Highlands",
    "Enga",
    "Gulf",
    "Madang",
    "Manus",
    "Milne Bay",
    "Morobe",
    "National Capital District",
    "New Ireland",
    "Northern",
    "Northern Solomons",
    "Southern Highlands",
    "West New Britain",
    "West Sepik",
    "Western",
    "Western Highlands"
  ],
  "Paracel Islands": [
    "Administrative unit not available"
  ],
  "Paraguay": [
    "Alto Paraguay",
    "Alto Parana",
    "Amambay",
    "Boqueron",
    "Caaguazu",
    "Caazapa",
    "Canindeyu",
    "Central",
    "Concepcion",
    "Cordillera",
    "Guaira",
    "Itapua",
    "Misiones",
    "Neembucu",
    "Paraguari",
    "Presidente Hayes",
    "San Pedro"
  ],
  "Peru": [
    "Amazonas",
    "Ancash",
    "Apur�mac",
    "Arequipa",
    "Ayacucho",
    "Cajamarca",
    "Callao",
    "Cusco",
    "Huancavelica",
    "Hu�nuco",
    "Ica",
    "Jun�n",
    "La Libertad",
    "Lambayeque",
    "Lima",
    "Loreto",
    "Madre de Dios",
    "Moquegua",
    "Pasco",
    "Piura",
    "Puno",
    "San Mart�n",
    "Tacna",
    "Tumbes",
    "Ucayali"
  ],
  "Philippines": [
    "Autonomous region in Muslim Mindanao (ARMM)",
    "Cordillera Administrative region (CAR)",
    "National Capital region (NCR)",
    "Region I (Ilocos region)",
    "Region II (Cagayan Valley)",
    "Region III (Central Luzon)",
    "Region IV (Southern Tagalog)",
    "Region IV-A (Calabarzon)",
    "Region IX (Zamboanga Peninsula)",
    "Region V (Bicol region)",
    "Region VI (Western Visayas)",
    "Region VII (Central Visayas)",
    "Region VIII (Eastern Visayas)",
    "Region X (Northern Mindanao)",
    "Region XI (Davao Region)",
    "Region XII (Soccsksargen)",
    "Region XIII (Caraga)"
  ],
  "Pitcairn": [
    "Administrative unit not available"
  ],
  "Poland": [
    "Dolnoslaskie",
    "Kujawsko-Pomorskie",
    "Lodzkie",
    "Lubeiskie",
    "Lubuskie",
    "Malopolske",
    "Mazowieckie",
    "Opolskie",
    "Podkarpackie",
    "Podlaskie",
    "Pomorskie",
    "Slaskie",
    "Swietokrzyskie",
    "Warminsko-Mazurskie",
    "Wielkopolskie",
    "Zachodnio-Pomorskie"
  ],
  "Portugal": [
    "Aveiro",
    "Beja",
    "Braga",
    "Braganca",
    "Castelo Branco",
    "Coimbra",
    "Evora",
    "Faro",
    "Guarda",
    "Leiria",
    "Lisboa",
    "Portalegre",
    "Porto",
    "Santarem",
    "Setubal",
    "Viana Do Castelo",
    "Vila Real",
    "Viseu"
  ],
  "Puerto Rico": [
    "Aguadilla",
    "Arecibo",
    "Bayamon",
    "Guayama",
    "Humacao",
    "Mayaguez",
    "Ponce",
    "San Juan"
  ],
  "Qatar": [
    "Ad Dawhah",
    "Al Ghuwayriyah",
    "Al Jumayliyah",
    "Al Khawr",
    "Al-wakrah",
    "Ar Rayyan",
    "Ash Shamal",
    "Jarayan Al Batnah",
    "Umm Salal"
  ],
  "Republic of Korea": [
    "Cheju-do",
    "Chollabuk-do",
    "Chollanam-do",
    "Chungchongbuk-do",
    "Chungchongnam-do",
    "Inchon",
    "Kang-won-do",
    "Kwangju",
    "Kyonggi-do",
    "Kyongsangbuk-do",
    "Kyongsangnam-do",
    "Pusan",
    "Seoul",
    "Taegu",
    "Taejon"
  ],
  "Romania": [
    "Alba",
    "Arad",
    "Arges",
    "Bacau",
    "Bihor",
    "Bistrita-nasaud",
    "Botosani",
    "Braila",
    "Brasov",
    "Bucuresti",
    "Buzau",
    "Calarasi",
    "Caras-severin",
    "Cluj",
    "Constanta",
    "Covasna",
    "Dimbovita",
    "Dolj",
    "Galati",
    "Giurgiu",
    "Gorj",
    "Harghita",
    "Hunedoara",
    "Ialomita",
    "Iasi",
    "Maramures",
    "Mehedinti",
    "Mures",
    "Neamt",
    "Olt",
    "Prahova",
    "Salaj",
    "Satu Mare",
    "Sibiu",
    "Suceava",
    "Teleorman",
    "Timis",
    "Tulcea",
    "Vaslui",
    "Vilcea",
    "Vrancea"
  ],
  "Russian Federation": [
    "Administrative unit not available",
    "Adygeya Rep.",
    "Aginskiy Buryatskiy A. Okrug",
    "Altay Rep.",
    "Altayskiy Kray",
    "Amurskaya Oblast",
    "Arkhangelskaya Oblast",
    "Astrakhanskaya Oblast",
    "Bashkortostan Rep.",
    "Belgorodskaya Oblast",
    "Bryanskaya Oblast",
    "Buryatiya Rep.",
    "Chechnya Rep.",
    "Chelyabinskaya Oblast",
    "Chitinskaya Oblast",
    "Chukotskiy Okrug",
    "Chuvashiya Rep.",
    "Dagestan Rep.",
    "Evenkiyskiy Okrug",
    "Ingushetiya Rep.",
    "Irkutskaya Oblast",
    "Ivanovskaya Oblast",
    "Kabardino-balkariya Rep.",
    "Kaliningradskaya Oblast",
    "Kalmykiya Rep.",
    "Kaluzhskaya Oblast",
    "Kamchatskaya Oblast",
    "Karatchayevo-cherkesiya Rep.",
    "Karelya Rep.",
    "Kemerovskaya Oblast",
    "Khabarovskiy Kray",
    "Khakasiya Rep.",
    "Khanty-mansyiskiy Okrug",
    "Kirovskaya Oblast",
    "Komi Rep.",
    "Komi-permyatskiy Okrug",
    "Koryakskiy Okrug",
    "Kostromskaya Oblast",
    "Krasnodarskiy Kray",
    "Krasnoyarskiy Kray",
    "Kurganskaya Oblast",
    "Kurskaya Oblast",
    "Leningradskaya Oblast",
    "Lipetskaya Oblast",
    "Magadanskaya Oblast",
    "Mariy-el Rep.",
    "Mordoviya Rep.",
    "Moskovskaya Oblast",
    "Moskva",
    "Murmanskaya Oblast",
    "Name Unknown",
    "Nenetskiy Okrug",
    "Nizhegorodskaya Oblast",
    "Novgorodskaya Oblast",
    "Novosibirskaya Oblast",
    "Omskaya Oblast",
    "Orenburgskaya Oblast",
    "Orlovskaya Oblast",
    "Penzenskaya Oblast",
    "Permskaya Oblast",
    "Primorskiy Kray",
    "Pskovskaya Oblast",
    "Rostovskaya Oblast",
    "Ryazanskaya Oblast",
    "Sakha Rep.",
    "Sakhalinskaya Oblast",
    "Samarskaya Oblast",
    "Sankt-peterburg",
    "Saratovskaya Oblast",
    "Severnaya Osetiya-alaniya Rep.",
    "Smolenskaya Oblast",
    "Stavropolskiy Kray",
    "Sverdlovskaya Oblast",
    "Tambovskaya Oblast",
    "Tatarstan Rep.",
    "Taymyrskiy Okrug",
    "Tomskaya Oblast",
    "Tulskaya Oblast",
    "Tverskaya Oblast",
    "Tyumenskaya Oblast",
    "Tyva Rep.",
    "Udmurtiya Rep.",
    "Ulyanovskaya Oblast",
    "Ustordynskiy Buryatskiy Okrug",
    "Vladimirskaya Oblast",
    "Volgogradskaya Oblast",
    "Vologodskaya Oblast",
    "Voronezhskaya Oblast",
    "Yamalo-nenetskiy Okrug",
    "Yaroslavskaya Oblast",
    "Yevreyskaya A. Oblast"
  ],
  "Rwanda": [
    "East/Iburasirazuba",
    "Kigali City/Umujyi wa Kigali",
    "North/Amajyaruguru",
    "South/Amajyepfo",
    "West/Iburengerazuba"
  ],
  "R�union": [
    "Arrondissement_du_vent",
    "Arrondissement_souse_le_vent"
  ],
  "Saint Helena": [
    "Ascension",
    "Saint Helena",
    "Tristan Da Cunha"
  ],
  "Saint Kitts and Nevis": [
    "Christ Church Nichola Town",
    "Saint Anne Sandy Point",
    "Saint George Basseterre",
    "Saint George Gingerland",
    "Saint James Windward",
    "Saint John Capisterre",
    "Saint John Figtree",
    "Saint Mary Cayon",
    "Saint Paul Capisterre",
    "Saint Paul Charlestown",
    "Saint Peter Basseterre",
    "Saint Thomas Lowland",
    "Saint Thomas Middle Island",
    "Trinity Palmetto Point"
  ],
  "Saint Lucia": [
    "Area Under National Administra",
    "Region Number 1",
    "Region Number 2",
    "Region Number 3",
    "Region Number 4",
    "Region Number 5",
    "Region Number 6",
    "Region Number 7",
    "Region Number 8"
  ],
  "Saint Pierre et Miquelon": [
    "Miquelon-Langlade",
    "Saint-Pierre"
  ],
  "Saint Vincent and the Grenadines": [
    "Charlotte",
    "Grenadines",
    "Saint Andrew",
    "Saint David",
    "Saint George",
    "Saint Patrick"
  ],
  "Samoa": [
    "Administrative unit not available"
  ],
  "San Marino": [
    "Administrative unit not available"
  ],
  "Sao Tome and Principe": [
    "Principe",
    "Sao Tome"
  ],
  "Saudi Arabia": [
    "Asir",
    "Baha",
    "Eastern Province",
    "Hail",
    "Jawf",
    "Jizan",
    "Madinah",
    "Makkah",
    "Najran",
    "Northern Frontier",
    "Quassim",
    "Riyad",
    "Tabuk"
  ],
  "Scarborough Reef": [
    "Administrative unit not available"
  ],
  "Senegal": [
    "Dakar",
    "Diourbel",
    "Fatick",
    "Kaffrine",
    "Kaolack",
    "Kedougou",
    "Kolda",
    "Louga",
    "Matam",
    "Saint louis",
    "Sedhiou",
    "Tambacounda",
    "Thies",
    "Ziguinchor"
  ],
  "Senkaku Islands": [
    "Administrative unit not available"
  ],
  "Serbia": [
    "Borski",
    "Branicevski",
    "Grad Beograd",
    "Jablanicki",
    "Juzno-backi",
    "Juzno-banatski",
    "Kolubarski",
    "Kosovski",
    "Kosovsko-mitrovatski",
    "Kosovsko-pomoravski",
    "Macvanski",
    "Moravicki",
    "Nisavski",
    "Pcinjski",
    "Pecki",
    "Pirotski",
    "Podunavski",
    "Pomoravski",
    "Prizremski",
    "Rasinski",
    "Raski",
    "Severno-backi",
    "Severno-banatski",
    "Srednje-banatski",
    "Sremski",
    "Sumadijski",
    "Toplicki",
    "Zajecarski",
    "Zapadno-backi",
    "Zlatiborski"
  ],
  "Seychelles": [
    "Aldabra",
    "Alphonse",
    "Anse Aux Pins",
    "Anse Boileau",
    "Anse Etoile",
    "Anse Royale",
    "Aride",
    "Assumption",
    "Astove",
    "Au Cap",
    "Baie Lazare",
    "Beau Vallon",
    "Bel Air",
    "Belombre",
    "Bijoutier",
    "Bird",
    "Cascade",
    "Cerf Island",
    "Coetivy",
    "Conception",
    "Cosmoledo",
    "Cousin",
    "Cousine",
    "Curieuse",
    "Darros",
    "Denis",
    "Desnoeufs",
    "Desroches",
    "English River",
    "Farquhar",
    "Felicite",
    "Fregate",
    "Glacis",
    "Grand Anse Mahe",
    "Grande Soeur",
    "Ile du Sud",
    "La Digue",
    "Les Mamelles",
    "Marie-Louise",
    "Mont Buxton",
    "Mont Fleuri",
    "North Island",
    "Petite Soeur",
    "Plaisance",
    "Platte",
    "Pointe Larue",
    "Poivre",
    "Port Glaud",
    "Praslin",
    "Providence",
    "Remire",
    "Roche Caiman",
    "Silhouette",
    "St Louis",
    "St. Francois",
    "St. Joseph Atoll",
    "St. Pierre",
    "Ste Anne",
    "Takamaka",
    "Therese"
  ],
  "Sierra Leone": [
    "Eastern",
    "Northern",
    "Southern",
    "Western Area"
  ],
  "Singapore": [
    "Ang Mo Kio-cheng San",
    "Bukit Timah",
    "Central Singapore",
    "Hougang",
    "Marine Parade",
    "Northeast",
    "Potong Pasir",
    "Sembawang-hong Kah",
    "Tanjong Pagar"
  ],
  "Slovakia": [
    "Banska Bystrica",
    "Bratislava",
    "Kosice",
    "Nitra",
    "Presov",
    "Trencin",
    "Trnava",
    "Zilna"
  ],
  "Slovenia": [
    "Gorenjska",
    "Goriska",
    "Jugovzodna Slovenija",
    "Koroska",
    "Notranjsko-kraska",
    "Obalno-kraska",
    "Osrednjeslovenska",
    "Podravska",
    "Pomurska",
    "Savinjska",
    "Spodnjeposavska",
    "Zasavska"
  ],
  "Solomon Islands": [
    "Administrative unit not available"
  ],
  "Somalia": [
    "Awdal",
    "Bakool",
    "Banadir",
    "Bari",
    "Bay",
    "Galgaduud",
    "Gedo",
    "Hiraan",
    "Juba Dhexe",
    "Juba Hoose",
    "Mudug",
    "Nugaal",
    "Sanaag",
    "Shabelle Dhexe",
    "Shabelle Hoose",
    "Sool",
    "Togdheer",
    "Woqooyi Galbeed"
  ],
  "South Africa": [
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "North West",
    "Northern Cape",
    "Western Cape"
  ],
  "South Georgia and the South Sandwich Islands": [
    "Administrative unit not available"
  ],
  "South Sudan": [
    "Central Equatoria",
    "Eastern Equatoria",
    "El Buheyrat",
    "Jonglei",
    "Northern Bahr El Ghazal",
    "Unity",
    "Upper Nile",
    "Warab",
    "Western Bahr El Ghazal",
    "Western Equatoria"
  ],
  "Spain": [
    "Andaluc�a",
    "Arag�n",
    "Canarias",
    "Cantabria",
    "Castilla y Le�n",
    "Castilla-La Mancha",
    "Catalu�a/Catalunya",
    "Ciudad Aut�noma de Ceuta",
    "Ciudad Aut�noma de Melilla",
    "Comunidad Foral de Navarra",
    "Comunidad de Madrid",
    "Comunitat Valenciana",
    "Extremadura",
    "Galicia",
    "Illes Balears",
    "La Rioja",
    "Pa�s Vasco/Euskadi",
    "Principado de Asturias",
    "Regi�n de Murcia"
  ],
  "Spratly Islands": [
    "Administrative unit not available"
  ],
  "Sri Lanka": [
    "Central",
    "Eastern",
    "North Central",
    "North Western",
    "Northern",
    "Sabaragamuwa",
    "Southern",
    "Uva",
    "Western"
  ],
  "Sudan": [
    "Al Jazeera",
    "Blue Nile",
    "Gadaref",
    "Kassala",
    "Khartoum",
    "Nile",
    "Northern",
    "Northern Darfur",
    "Northern Kordofan",
    "Red Sea",
    "Sennar",
    "Southern Darfur",
    "Southern Kordofan",
    "Western Darfur",
    "White Nile"
  ],
  "Suriname": [
    "Brokopondo",
    "Commewijne",
    "Coronie",
    "Marowijne",
    "Nickerie",
    "Para",
    "Paramaribo",
    "Saramacca",
    "Sipaliwini",
    "Wanica"
  ],
  "Svalbard and Jan Mayen Islands": [
    "Administrative unit not available"
  ],
  "Swaziland": [
    "Hhohho",
    "Lubombo",
    "Manzini",
    "Shiselweni"
  ],
  "Sweden": [
    "Blekinge Laen",
    "Dalarnas Laen",
    "Gaevleborgs Laen",
    "Gotlands Laen",
    "Hallands Laen",
    "Jaemtlands Laen",
    "Joenkoepings Laen",
    "Kalmar Laen",
    "Kronobergs Laen",
    "Norrbottens Laen",
    "Oerebro Laen",
    "Oestergoetlands Laen",
    "Skaane Laen",
    "Soedermanlands Laen",
    "Stockholms Laen",
    "Uppsala Laen",
    "Vaermlands Laen",
    "Vaesterbottens Laen",
    "Vaesternorrlands Laen",
    "Vaestmanlands Laen",
    "Vaestra Goetalands Laen"
  ],
  "Switzerland": [
    "Aargau",
    "Appenzell Ausser-rhoden",
    "Appenzell Inner-rhoden",
    "Basel-landschaft",
    "Basel-stadt",
    "Bern",
    "Fribourg",
    "Geneve",
    "Glarus",
    "Graubunden",
    "Jura",
    "Luzern",
    "Neuchatel",
    "Nidwalden",
    "Obwalden",
    "Sankt Gallen",
    "Schaffhausen",
    "Schwyz",
    "Solothurn",
    "Thurgau",
    "Ticino",
    "Uri",
    "Valais",
    "Vaud",
    "Zug",
    "Zurich"
  ],
  "Syrian Arab Republic": [
    "Al_Qunaytirah",
    "Aleppo",
    "As_Suweida",
    "City_Damascus",
    "Damascus",
    "Dara",
    "Dayr_Az_Zor",
    "Hama",
    "Hassakeh",
    "Homs",
    "Idleb",
    "Lattakia",
    "Raqqa",
    "Tartous"
  ],
  "Taiwan": [
    "Taiwan Sheng"
  ],
  "Tajikistan": [
    "Badakhshoni Kuni",
    "Khatlon",
    "Sogd",
    "Tadzhikistan Territories"
  ],
  "Thailand": [
    "Amnat Charoen",
    "Ang Thong",
    "Bangkok",
    "Buriram",
    "Chachoengsao",
    "Chainat",
    "Chaiyaphum",
    "Chanthaburi",
    "Chiang Mai",
    "Chiang Rai",
    "Chonburi",
    "Chumphon",
    "Kalasin",
    "Kampaeng Phet",
    "Kanchanaburi",
    "Khon Kaen",
    "Krabi",
    "Lampang",
    "Lamphun",
    "Loei",
    "Lopburi",
    "Mae Hong Son",
    "Maha Sarakham",
    "Mukdahan",
    "Nakhon Nayok",
    "Nakhon Pathom",
    "Nakhon Phanom",
    "Nakhon Ratchasima",
    "Nakhon Sawan",
    "Nakhon Si Thammarat",
    "Nan",
    "Narathiwat",
    "Nong Bua Lamphu",
    "Nong Khai",
    "Nonthaburi",
    "Pathum Thani",
    "Pattani",
    "Phachinburi",
    "Phangnga",
    "Phatthalung",
    "Phayao",
    "Phetchabun",
    "Phetchaburi",
    "Phichit",
    "Phitsanulok",
    "Phra Nakhon Si Ayudhya",
    "Phrae",
    "Phuket",
    "Prachuap Khilikhan",
    "Ranong",
    "Ratchaburi",
    "Rayong",
    "Roi Et",
    "Sa Kaeo",
    "Sakon Nakhon",
    "Samut Prakarn",
    "Samut Sakhon",
    "Samut Songkham",
    "Saraburi",
    "Satun",
    "Si Saket",
    "Singburi",
    "Songkhla",
    "Sukhothai",
    "Suphanburi",
    "Surat Thani",
    "Surin",
    "Tak",
    "Trad",
    "Trang",
    "Ubon Ratchathani",
    "Udon Thani",
    "Uthai Thani",
    "Uttaradit",
    "Yala",
    "Yasothon"
  ],
  "The former Yugoslav Republic of Macedonia": [
    "Berovo",
    "Bitola",
    "Brod",
    "Debar",
    "Delcevo",
    "Demir Hisar",
    "Gevgelija",
    "Gostivar",
    "Kavadarci",
    "Kicevo",
    "Kocani",
    "Kratovo",
    "Kriva Palanka",
    "Krusevo",
    "Kumanovo",
    "Negotino",
    "Ohrid",
    "Prilep",
    "Probistip",
    "Radovic",
    "Resen",
    "Skopje",
    "Stip",
    "Struga",
    "Strumica",
    "Sveti Nikole",
    "Tetovo",
    "Valandovo",
    "Veles",
    "Vinica"
  ],
  "Timor-Leste": [
    "Aileu",
    "Ainaro",
    "Baucau",
    "Bobonaro",
    "Covalima",
    "Dili",
    "Ermera",
    "Lautem",
    "Liquica",
    "Manatuto",
    "Manufahi",
    "Oecussi",
    "Viqueque"
  ],
  "Togo": [
    "Centrale",
    "Kara",
    "Maritime",
    "Plateaux",
    "Savanes"
  ],
  "Tokelau": [
    "Administrative unit not available"
  ],
  "Tonga": [
    "Administrative unit not available"
  ],
  "Trinidad and Tobago": [
    "Arima",
    "Chaguanas",
    "Couva/Tabaquite/Talparo",
    "Diego Martin",
    "Penal/Debe",
    "Point Fortin",
    "Port Of Spain",
    "Princes Town",
    "Rio Claro/Mayaro",
    "San Fernando",
    "San Juan/Laventille",
    "Sangre Grande",
    "Siparia",
    "Tobago",
    "Tunapuna/Piarco"
  ],
  "Tromelin Island": [
    "Administrative unit not available"
  ],
  "Tunisia": [
    "Ariana",
    "Beja",
    "Ben Arous",
    "Bizerte",
    "Gabes",
    "Gafsa",
    "Jendouba",
    "Kairouan",
    "Kasserine",
    "Kebili",
    "Le Kef",
    "Mahdia",
    "Manouba",
    "Medenine",
    "Monastir",
    "Nabeul",
    "Sfax",
    "Sidi Bouz",
    "Siliana",
    "Sousse",
    "Tataouine",
    "Tozeur",
    "Tunis",
    "Zaghouan"
  ],
  "Turkey": [
    "Adana",
    "Adiyaman",
    "Afyon",
    "Agri",
    "Aksaray",
    "Amasya",
    "Ankara",
    "Antalya",
    "Ardahan",
    "Artvin",
    "Aydin",
    "Balikesir",
    "Bartin",
    "Batman",
    "Bayburt",
    "Bilecik",
    "Bingol",
    "Bitlis",
    "Bolu",
    "Burdur",
    "Bursa",
    "Canakkale",
    "Cankiri",
    "Corum",
    "Denizli",
    "Diyarbakir",
    "Edirne",
    "Elazig",
    "Erzincan",
    "Erzurum",
    "Eskisehir",
    "Gaziantep",
    "Giresun",
    "Gumushane",
    "Hakkari",
    "Hatay",
    "Icel",
    "Igdir",
    "Isparta",
    "Istanbul",
    "Izmir",
    "K.maras",
    "Karabuk",
    "Karaman",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kilis",
    "Kirikkale",
    "Kirklareli",
    "Kirsehir",
    "Kocaeli",
    "Konya",
    "Kutahya",
    "Malatya",
    "Manisa",
    "Mardin",
    "Mugla",
    "Mus",
    "Nevsehir",
    "Nigde",
    "Ordu",
    "Osmaniye",
    "Rize",
    "Sakarya",
    "Samsun",
    "Sanliurfa",
    "Siirt",
    "Sinop",
    "Sirnak",
    "Sivas",
    "Tekirdag",
    "Tokat",
    "Trabzon",
    "Tunceli",
    "Usak",
    "Van",
    "Yalova",
    "Yozgat",
    "Zonguldak"
  ],
  "Turkmenistan": [
    "Administrative unit not available",
    "Ahal",
    "Balkan",
    "Chardzhou",
    "Mary",
    "Tashauz"
  ],
  "Turks and Caicos islands": [
    "Grand Turk",
    "Middle Caicos",
    "North Caicos",
    "Providenciales and West Caicos",
    "Salt City",
    "South and East Caicos"
  ],
  "Tuvalu": [
    "Administrative unit not available"
  ],
  "U.K. of Great Britain and Northern Ireland": [
    "England",
    "Northern Ireland",
    "Scotland",
    "Wales"
  ],
  "Uganda": [
    "Abim",
    "Adjumani",
    "Agago",
    "Alebtong",
    "Amolatar",
    "Amudat",
    "Amuria",
    "Amuru",
    "Apac",
    "Arua",
    "Budaka",
    "Bududa",
    "Bugiri",
    "Buhweju",
    "Buikwe",
    "Bukedea",
    "Bukomansimbi",
    "Bukwo",
    "Bulambuli",
    "Buliisa",
    "Bundibugyo",
    "Bushenyi",
    "Busia",
    "Butaleja",
    "Butambala",
    "Buvuma",
    "Buyende",
    "Dokolo",
    "Gomba",
    "Gulu",
    "Hoima",
    "Ibanda",
    "Iganga",
    "Isingiro",
    "Jinja",
    "Kaabong",
    "Kabale",
    "Kabarole",
    "Kaberamaido",
    "Kalangala",
    "Kaliro",
    "Kalungu",
    "Kampala",
    "Kamuli",
    "Kamwenge",
    "Kanungu",
    "Kapchorwa",
    "Kasese",
    "Katakwi",
    "Kayunga",
    "Kibaale",
    "Kibuku",
    "Kiruhura",
    "Kiryandongo",
    "Kisoro",
    "Kitgum",
    "Koboko",
    "Kole",
    "Kotido",
    "Kumi",
    "Kween",
    "Kyankwanzi",
    "Kyegegwa",
    "Kyenjojo",
    "Lamwo",
    "Lira",
    "Luuka",
    "Luwero",
    "Lwengo",
    "Lyantonde",
    "Manafwa",
    "Maracha",
    "Masaka",
    "Masindi",
    "Mayuge",
    "Mbale",
    "Mbarara",
    "Mitooma",
    "Mityana",
    "Moroto",
    "Moyo",
    "Mpigi",
    "Mubende",
    "Mukono",
    "Nakapiripirit",
    "Nakaseke",
    "Nakasongola",
    "Namayingo",
    "Namutumba",
    "Napak",
    "Nebbi",
    "Ngora",
    "Ntoroko",
    "Ntungamo",
    "Nwoya",
    "Otuke",
    "Oyam",
    "Pader",
    "Pallisa",
    "Rakai",
    "Rubirizi",
    "Rukungiri",
    "Serere",
    "Sheema",
    "Sironko",
    "Soroti",
    "Ssembabule",
    "Tororo",
    "Wakiso",
    "Yumbe",
    "Zombo"
  ],
  "Ukraine": [
    "Cherkas'ka",
    "Chernihivs'ka",
    "Chernivets'ka",
    "Dnipropetrovs'ka",
    "Donets'ka",
    "Ivano-frankivs'ka",
    "Kharkivs'ka",
    "Khersons'ka",
    "Khmel'nyts'ka",
    "Kirovohrads'ka",
    "Krym",
    "Kyyivs'ka",
    "L'vivs'ka",
    "Luhans'ka",
    "Mykolayivs'ka",
    "Odes'ka",
    "Poltavs'ka",
    "Rivnens'ka",
    "Sums'ka",
    "Ternopil's'ka",
    "Vinnyts'ka",
    "Volyns'ka",
    "Zakarpats'ka",
    "Zaporiz'ka",
    "Zhytomyrs'ka"
  ],
  "United Arab Emirates": [
    "Abu Dhabi",
    "Ajman",
    "Dubai",
    "Fujairah",
    "Ras Al Khaimah",
    "Sharjah",
    "Umm AL Quwain"
  ],
  "United Republic of Tanzania": [
    "Arusha",
    "Dar-es-salaam",
    "Dodoma",
    "Geita",
    "Iringa",
    "Kagera",
    "Kaskazini Pemba",
    "Kaskazini Unguja",
    "Katavi",
    "Kigoma",
    "Kilimanjaro",
    "Kusini Pemba",
    "Kusini Unguja",
    "Lindi",
    "Manyara",
    "Mara",
    "Mbeya",
    "Mjini Magharibi",
    "Morogoro",
    "Mtwara",
    "Mwanza",
    "Njombe",
    "Pwani",
    "Rukwa",
    "Ruvuma",
    "Shinyanga",
    "Simiyu",
    "Singida",
    "Tabora",
    "Tanga"
  ],
  "United States Virgin Islands": [
    "Saint Croix (County Equivalent)",
    "Saint John (County Equivalent)",
    "Saint Thomas (County Equivalent)"
  ],
  "United States of America": [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming"
  ],
  "Uruguay": [
    "Artigas",
    "Canelones",
    "Cerro Largo",
    "Colonia",
    "Durazno",
    "Flores",
    "Florida",
    "Lavalleja",
    "Maldonado",
    "Montevideo",
    "Paysandu",
    "Rio Negro",
    "Rivera",
    "Rocha",
    "Salto",
    "San Jose",
    "Soriano",
    "Tacuarembo",
    "Treinta Y Tres"
  ],
  "Uzbekistan": [
    "Andijan",
    "Bukhara",
    "Fergana",
    "Jizzakh",
    "Karakalpakstan",
    "Kashkadarya",
    "Khorezm",
    "Namangan",
    "Navoiy",
    "Samarkand",
    "Sirdarya",
    "Surkhandarya",
    "Tashkent",
    "Tashkent city"
  ],
  "Vanuatu": [
    "Malampa",
    "Penama",
    "Sanma",
    "Shefa",
    "Tafea",
    "Torba"
  ],
  "Venezuela": [
    "Amazonas",
    "Anzoategui",
    "Apure",
    "Aragua",
    "Barinas",
    "Bolivar",
    "Carabobo",
    "Cojedes",
    "Delta Amacuro",
    "Dependencias Federales",
    "Distrito Capital",
    "Falcon",
    "Guarico",
    "Lara",
    "Merida",
    "Miranda",
    "Monagas",
    "Nueva Esparta",
    "Portuguesa",
    "Sucre",
    "Tachira",
    "Trujillo",
    "Vargas",
    "Yaracuy",
    "Zulia"
  ],
  "Viet Nam": [
    "An Giang",
    "Ba Ria-Vung Tau",
    "Bac Giang",
    "Bac Kan",
    "Bac Lieu",
    "Bac Ninh",
    "Ben Tre",
    "Binh Dinh",
    "Binh Duong",
    "Binh Phuoc",
    "Binh Thuan",
    "Ca Mau",
    "Can Tho city",
    "Cao Bang",
    "Da Nang City",
    "Dak Lak",
    "Dak Nong",
    "Dien Bien",
    "Dong Nai",
    "Dong Thap",
    "Gia Lai",
    "Ha Giang",
    "Ha Nam",
    "Ha Noi City",
    "Ha Tay",
    "Ha Tinh",
    "Hai Duong",
    "Hai Phong City",
    "Hau Giang",
    "Ho Chi Minh City",
    "Hoa Binh",
    "Hung Yen",
    "Khanh Hoa",
    "Kien Giang",
    "Kon Tum",
    "Lai Chau",
    "Lam Dong",
    "Lang Son",
    "Lao Cai",
    "Long An",
    "Nam Dinh",
    "Nghe An",
    "Ninh Binh",
    "Ninh Thuan",
    "Phu Tho",
    "Phu Yen",
    "Quang Binh",
    "Quang Nam",
    "Quang Ngai",
    "Quang Ninh",
    "Quang Tri",
    "Soc Trang",
    "Son La",
    "Tay Ninh",
    "Thai Binh",
    "Thai Nguyen",
    "Thanh Hoa",
    "Thua Thien - Hue",
    "Tien Giang",
    "Tra Vinh",
    "Tuyen Quang",
    "Vinh Long",
    "Vinh Phuc",
    "Yen Bai"
  ],
  "Wake Island": [
    "Administrative unit not available"
  ],
  "Wallis and Futuna": [
    "Administrative unit not available"
  ],
  "West Bank": [
    "Administrative unit not available",
    "Al Khalil (Hebron)",
    "Al Quds (Jerusalem)",
    "Ariha (Jericho)",
    "Bethlehem",
    "Jenin",
    "Nablus",
    "Qalqiliya",
    "Ramallah",
    "Salfit",
    "Tubas",
    "Tulkarm"
  ],
  "Western Sahara": [
    "Rio De Oro",
    "Saguia El Hamra"
  ],
  "Yemen": [
    "Abyan",
    "Aden",
    "Al Bayda",
    "Al Dhale'e",
    "Al Hudaydah",
    "Al Jawf",
    "Al Maharah",
    "Al Mahwit",
    "Amanat Al Asimah",
    "Amran",
    "Dhamar",
    "Hadramaut",
    "Hajjah",
    "Ibb",
    "Lahj",
    "Marib",
    "Raymah",
    "Sa'ada",
    "Sana'a",
    "Shabwah",
    "Taizz"
  ],
  "Zambia": [
    "Central",
    "Copperbelt",
    "Eastern",
    "Luapula",
    "Lusaka",
    "North-Western",
    "Northern",
    "Southern",
    "Western"
  ],
  "Zimbabwe": [
    "Bulawayo",
    "Harare",
    "Manicaland",
    "Mashonaland Central",
    "Mashonaland East",
    "Mashonaland West",
    "Masvingo",
    "Matabeleland North",
    "Matabeleland South",
    "Midlands"
  ]
};


exports.admin_boundaries = getAdminBoundaryNames;
exports.countries = country_names;
